#install with pip install -e .
[project]
name="mlops_qa_bot"
version="0.1.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]

[tool.pytest.ini_options]
testpaths = ["tests"]